### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBuffer' of undefined

### ISSUE THREAD

**Issue by angelbotto** [benwbooth/atom-screen-send#1]
**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [screen-send](https://github.com/benwbooth/atom-screen-send) package, v1.10.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getBuffer' of undefined

```
At /Users/angelbotto/.atom/packages/screen-send/lib/screen-send.coffee:56

TypeError: Cannot read property 'getBuffer' of undefined
  at ScreenSendView.callback (/Users/angelbotto/.atom/packages/screen-send/lib/screen-send.coffee:56:51)
  at ScreenSendView.module.exports.ScreenSendView.confirmed (/Users/angelbotto/.atom/packages/screen-send/lib/screen-send-view.coffee:20:5)
  at ScreenSendView.module.exports.SelectListView.confirmSelection (/Users/angelbotto/.atom/packages/screen-send/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Users/angelbotto/.atom/packages/screen-send/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)

```

### Commands

```
     -1:36.2.0 core:move-to-top (atom-text-editor.editor.is-focused)
 92x -1:35.8.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -1:27.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:27 core:cut (atom-text-editor.editor.is-focused)
     -1:26.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:26.2.0 core:cut (atom-text-editor.editor.is-focused)
     -1:24.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:24.4.0 core:save (atom-text-editor.editor.is-focused)
     -1:23.6.0 core:move-to-top (atom-text-editor.editor.is-focused)
     -0:22.7.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:22.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:18.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.3.0 command-palette:toggle (div.package-detail.panels-item)
     -0:02.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.3.0 screen-send:list (div.package-detail.panels-item)
     -0:01.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view",
      "vim-mode",
      "status-bar",
      "tool-bar"
    ],
    "ignoredNames": [
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db"
    ],
    "projectHome": "/Users/angelbotto/dev",
    "themes": [
      "one-dark-ui",
      "duotone-dark-sea-syntax"
    ]
  },
  "screen-send": {
    "terminalType": "Tmux"
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.22.0
api-workbench, v0.8.31
atom-jade, v0.3.0
duotone-dark-sea-syntax, v1.0.0
git-diff-details, v1.3.0
git-log, v0.4.1
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
imdone-atom-github, v0.1.11
language-babel, v2.28.0
language-ini, v1.16.0
language-ocaml, v1.1.2
language-thrift, v1.0.2
language-tmux, v0.4.0
linter, v1.11.11
linter-raml-myrules, v0.0.6
merge-conflicts, v1.4.4
nuclide, v0.141.0
outline-selection, v0.2.3
pigments, v0.29.2
raml, v0.2.0
screen-send, v1.10.0
sync-settings, v0.7.2
tabasco, v0.5.0
wakatime, v6.0.9

# Dev
No dev packages
```

**Comment by angelbotto** [comment]
**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [screen-send](https://github.com/benwbooth/atom-screen-send) package, v1.10.0


### Stack Trace

Uncaught TypeError: Cannot read property 'getBuffer' of undefined

```
At /Users/angelbotto/.atom/packages/screen-send/lib/screen-send.coffee:62

TypeError: Cannot read property 'getBuffer' of undefined
  at Object.module.exports.ScreenSend.send (/Users/angelbotto/.atom/packages/screen-send/lib/screen-send.coffee:62:49)
  at atom-workspace.subscriptions.add.atom.commands.add.screen-send:send (/Users/angelbotto/.atom/packages/screen-send/lib/screen-send.coffee:42:31)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)

```

### Commands

```
     -1:34 core:cut (atom-text-editor.editor.is-focused)
     -1:32.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:32.2.0 core:save (atom-text-editor.editor.is-focused)
     -1:31.4.0 core:move-to-top (atom-text-editor.editor.is-focused)
     -0:30.5.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:30.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:26.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:12.1.0 command-palette:toggle (div.package-detail.panels-item)
     -0:10.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:10 screen-send:list (div.package-detail.panels-item)
     -0:09.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:05.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:02.7.0 command-palette:toggle (div.package-detail.panels-item)
     -0:00.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 screen-send:send (div.package-detail.panels-item)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view",
      "vim-mode",
      "status-bar",
      "tool-bar"
    ],
    "ignoredNames": [
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db"
    ],
    "projectHome": "/Users/angelbotto/dev",
    "themes": [
      "one-dark-ui",
      "duotone-dark-sea-syntax"
    ]
  },
  "screen-send": {
    "terminalType": "Tmux"
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.22.0
api-workbench, v0.8.31
atom-jade, v0.3.0
duotone-dark-sea-syntax, v1.0.0
git-diff-details, v1.3.0
git-log, v0.4.1
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
imdone-atom-github, v0.1.11
language-babel, v2.28.0
language-ini, v1.16.0
language-ocaml, v1.1.2
language-thrift, v1.0.2
language-tmux, v0.4.0
linter, v1.11.11
linter-raml-myrules, v0.0.6
merge-conflicts, v1.4.4
nuclide, v0.141.0
outline-selection, v0.2.3
pigments, v0.29.2
raml, v0.2.0
screen-send, v1.10.0
sync-settings, v0.7.2
tabasco, v0.5.0
wakatime, v6.0.9

# Dev
No dev packages
```

**Comment by benwbooth** [comment]
Does v1.11.0 fix the problem for you? Also, are you trying to send text from a read-only buffer or an empty window? It's weird that getBuffer is returning undefined for you; I can't seem to reproduce it in normal usage.

**Comment by angelbotto** [comment]
yes fixed thanks!!
