### ISSUE TITLE
Uncaught Error: Command failed: osascript -e tell application "iTerm" to tell windows to tell tab...

### ISSUE THREAD

**Issue by nfoti** [benwbooth/atom-screen-send#2]
[Enter steps to reproduce below:]
1. Edit a Python Script with multiple iTerm windows open (one of which launched Atom).
2. Press either F4 or F5.

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [screen-send](https://github.com/benwbooth/atom-screen-send) package, v1.11.0
### Stack Trace

Uncaught Error: Command failed: osascript -e tell application "iTerm" to tell windows to tell tabs to return sessions
49:53: execution error: The variable tabs is not defined. (-2753)

```
At child_process.js:499

Error: Command failed: osascript -e tell application "iTerm" to tell windows to tell tabs to return sessions
49:53: execution error: The variable tabs is not defined. (-2753)

    at checkExecSyncError (child_process.js:476:13)
    at execFileSync (child_process.js:496:13)
    at module.(anonymous function) (ATOM_SHELL_ASAR.js:159:20)
    at module.(anonymous function) (ATOM_SHELL_ASAR.js:159:20)
    at Object.module.exports.ScreenSend.itermSessions (/Users/nfoti/.atom/packages/screen-send/lib/screen-send.coffee:150:14)
    at Object.<anonymous> (/Users/nfoti/.atom/packages/screen-send/lib/screen-send.coffee:48:28)
    at Object.module.exports.ScreenSend.list (/Users/nfoti/.atom/packages/screen-send/lib/screen-send.coffee:47:16)
    at atom-workspace.subscriptions.add.atom.commands.add.screen-send:list (/Users/nfoti/.atom/packages/screen-send/lib/screen-send.coffee:40:31)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
  2x -2:44.7.0 vim-mode-plus:delete (atom-text-editor.editor.vim-mode-plus.is-focused.visual-mode.linewise)
     -2:43.4.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.operator-pending-mode.delete-pending)
     -2:43.2.0 vim-mode-plus:undo (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  2x -2:42.6.0 vim-mode-plus:delete (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -2:41.9.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -2:41.4.0 vim-mode-plus:move-to-beginning-of-line (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -2:41 vim-mode-plus:delete (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -2:40.9.0 vim-mode-plus:move-right (atom-text-editor.editor.vim-mode-plus.is-focused.operator-pending-mode.delete-pending)
     -2:39.5.0 vim-mode-plus:move-to-next-word (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -2:39.4.0 vim-mode-plus:move-to-first-character-of-line-down (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -2:38.6.0 core:save (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -2:35.7.0 vim-mode-plus:activate-linewise-visual-mode (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -2:34.6.0 script:run (atom-text-editor.editor.vim-mode-plus.is-focused.visual-mode.linewise)
     -1:00.3.0 settings-view:open (atom-text-editor.editor.vim-mode-plus.visual-mode.linewise.is-focused)
     -0:55.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.7.0 screen-send:list (atom-text-editor.editor.vim-mode-plus.visual-mode.linewise.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
minimap, v4.24.6
minimap-codeglance, v0.4.5
screen-send, v1.11.0
script, v3.7.3
vim-mode-plus, v0.46.0

# Dev
No dev packages
```

**Comment by benwbooth** [comment]
What version of iTerm are you using? I recently updated this package to work with iTerm 3.0, so it's not backward compatible with iTerm 2.0. Can you try upgrading to iTerm 3 and see if the problem persists?

**Comment by nfoti** [comment]
I'm using iTerm 3.0.4. Strangely, the plugin works fine when `Terminal Type` is `Tmux`, but not iTerm2.

Thanks.

**Comment by benwbooth** [comment]
I upgraded to iTerm 3.0.4, and I can't reproduce this. However, if I remove iTerm 3.0.4 and reinstall version 2.1.4, I get exactly what you are seeing. 

Are you sure you don't have an old version of iTerm lying around? Maybe search for iTerm in spotlight and see if you get more than 1 result returned. Also try emptying your trash. It could be that osascript is finding the wrong version of iTerm.

**Comment by nfoti** [comment]
I did in fact have two versions of iTerm installed (2.1.4 and 3.0.4) and have since removed 2.1.4 bust still get the same error. I tried uninstalling the plugin after removing iTerm 2.1.4 and still get the same error. Is there anything else I can try that would helpe the debugging process?

**Comment by janstieler** [comment]
Hi have installed iTerm 2 3.1.5 and I get also this error.
