### ISSUE TITLE
spawnSync osascript ENOENT

### ISSUE THREAD

**Issue by marmelin** [benwbooth/atom-screen-send#4]
[Enter steps to reproduce:]

1. Install screen-send
2. Press F4 or F5

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Windows 10
**Thrown From**: [screen-send](https://github.com/benwbooth/atom-screen-send) package 1.11.0

### Stack Trace

Uncaught Error: spawnSync osascript ENOENT

```
At child_process.js:518

Error: spawnSync osascript ENOENT
    at exports._errnoException (util.js:1026:11)
    at spawnSync (child_process.js:473:20)
    at execFileSync (child_process.js:510:13)
    at module.(anonymous function) (ELECTRON_ASAR.js:168:20)
    at Object.itermSessions (/packages/screen-send/lib/screen-send.coffee:150:14)
    at /packages/screen-send/lib/screen-send.coffee:48:28)
    at Object.list (/packages/screen-send/lib/screen-send.coffee:47:16)
    at /packages/screen-send/lib/screen-send.coffee:40:31)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.2/resources/app/src/command-registry.js:265:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.17.2/resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.17.2/resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -1:57.7.0 screen-send:list (input.hidden-input)
     -1:55.8.0 screen-send:send (input.hidden-input)
     -0:05.9.0 screen-send:list (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
angularjs 0.4.0 
angularjs-snippets 0.10.18 
atom-beautify 0.29.26 
atom-clock 0.1.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.4 
auto-detect-indentation 1.3.0 
busy-signal 1.4.3 
cssbeautify 1.3.0 
highlight-selected 0.13.1 
intentions 1.1.2 
linter 2.1.4 
linter-csslint 1.3.4 
linter-htmlhint 1.3.3 
linter-jshint 3.1.2 
linter-ui-default 1.6.0 
minimap 4.28.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.0 
minimap-pigments 0.2.2 
minimap-selection 4.4.0 
monokai-seti 0.9.0 
open-recent 5.0.0 
pigments 0.39.1 
remote-edit 1.9.0 
save-workspace 0.4.0 
screen-send 1.11.0 
seti-icons 1.5.3 
seti-ui 1.8.0 
```

**Comment by marmelin** [comment]
To old and I dont care anymore ...
