### ISSUE TITLE
Uncaught Error: spawnSync osascript ENOENT

### ISSUE THREAD

**Issue by CHOWY0152** [benwbooth/atom-screen-send#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [screen-send](https://github.com/benwbooth/atom-screen-send) package 1.11.0

### Stack Trace

Uncaught Error: spawnSync osascript ENOENT

```
At child_process.js:525

Error: spawnSync osascript ENOENT
    at exports._errnoException (util.js:1022:11)
    at spawnSync (child_process.js:480:20)
    at execFileSync (child_process.js:517:13)
    at module.(anonymous function) (ELECTRON_ASAR.js:173:20)
    at Object.itermSessions (/packages/screen-send/lib/screen-send.coffee:150:14)
    at /packages/screen-send/lib/screen-send.coffee:48:28)
    at Object.list (/packages/screen-send/lib/screen-send.coffee:47:16)
    at /packages/screen-send/lib/screen-send.coffee:40:31)
    at CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/atom/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:26.3.0 core:close (input.hidden-input)
     -0:06.5.0 screen-send:list (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.9.5 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
goto-definition 1.3.4 
intentions 1.1.5 
linter 2.2.0 
linter-flake8 2.2.1 
linter-ui-default 1.6.10 
screen-send 1.11.0 
set-indent 0.1.1 
show-spaces-tabs 1.0.0 
space-tab 0.4.2 
tabs-to-spaces 1.0.3 
teletype 0.2.3 
trailing-spaces 0.4.0 
```

**Comment by CHOWY0152** [comment]
This is resolved, after installing Konsole and Tmux instead of using the default Ubunutu Terminal.
