### ISSUE TITLE
Uncaught Callback must be a function

### ISSUE THREAD

**Issue by sboer** [benwbooth/atom-screen-send#7]
[Enter steps to reproduce:]

Just updated Atom and resetted to default settings because of troubles with the screen-send package. Now a new problem has appeared. By pressing F5 with the marker inside a code block, I get this error message. 

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [screen-send](https://github.com/benwbooth/atom-screen-send) package 1.11.0

### Stack Trace

Uncaught Callback must be a function

```
At fs.js:157

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:157:9)
    at Object.fs.write (fs.js:674:14)
    at Object.itermSend (/packages/screen-send/lib/screen-send.coffee:158:8)
    at Object.sendText (/packages/screen-send/lib/screen-send.coffee:83:12)
    at Object.send (/packages/screen-send/lib/screen-send.coffee:79:6)
    at ScreenSendView.callback (/packages/screen-send/lib/screen-send.coffee:59:8)
    at ScreenSendView.module.exports.ScreenSendView.confirmed (/packages/screen-send/lib/screen-send-view.coffee:20:5)
    at ScreenSendView.module.exports.SelectListView.confirmSelection (/packages/screen-send/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at /packages/screen-send/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
    at HTMLOListElement.dispatch (/packages/screen-send/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLOListElement.elemData.handle (/packages/screen-send/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:18.5.0 screen-send:send (input.hidden-input)
```

### Non-Core Packages

```
document-outline 2.1.2 
language-markdown 0.37.0 
line-number-color 0.2.0 
markdown-preview-enhanced 0.16.3 
screen-send 1.11.0 
```

**Comment by benwbooth** [comment]
Sorry, I don't use atom anymore. Does anyone want to adopt this package or submit a pull request?

Thanks!
